// Generated by CoffeeScript 1.7.1
(function() {
  var DISPLAY_HEIGHT, DISPLAY_WIDTH, KayoGameOverScene, KayoGameScene, KayoGameSceneBackAction, KayoGameSceneChara, KayoGameSceneRin, MenuScene, MenuSceneKayo, MenuSceneLabel, TitleLabel, TitleName, TitleScene, core,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  DISPLAY_WIDTH = 930;

  DISPLAY_HEIGHT = 620;

  enchant();

  core = {};

  TitleScene = (function(_super) {
    __extends(TitleScene, _super);

    function TitleScene() {
      TitleScene.__super__.constructor.call(this);
      this.bg = new Sprite(DISPLAY_WIDTH, DISPLAY_HEIGHT);
      this.bg.image = core.assets['./img/title_back1.jpg'];
      this.titlename = new TitleName();
      this.titlelabel = new TitleLabel();
      this.addChild(this.bg);
      this.addChild(this.titlename);
      this.addChild(this.titlelabel);
    }

    TitleScene.prototype.ontouchend = function() {
      core.menuScene = new MenuScene();
      return core.pushScene(core.menuScene);
    };

    return TitleScene;

  })(Scene);

  TitleName = (function(_super) {
    __extends(TitleName, _super);

    function TitleName() {
      TitleName.__super__.constructor.call(this, 657, 110);
      this.titleNameState = 'up';
      this.image = core.assets['./img/title_name.png'];
      this.x = 137;
      this.y = 255;
    }

    TitleName.prototype.onenterframe = function() {
      if (this.titleNameState === 'up') {
        this.y -= 1;
        if (this.y === 220) {
          return this.titleNameState = 'down';
        }
      } else if (this.titleNameState === 'down') {
        this.y += 1;
        if (this.y === 290) {
          return this.titleNameState = 'up';
        }
      }
    };

    return TitleName;

  })(Sprite);

  TitleLabel = (function(_super) {
    __extends(TitleLabel, _super);

    function TitleLabel() {
      TitleLabel.__super__.constructor.call(this);
      this.title_op = 'up';
      this.text = 'クリックしてスタート！';
      this.width = core.width;
      this.textAlign = 'center';
      this.font = '38px cursive';
      this.opacity = 0;
      this.y = 450;
      this.color = 'white';
    }

    TitleLabel.prototype.onenterframe = function() {
      if (this.title_op === 'up') {
        this.opacity += (new Date()).getMilliseconds() / 25000;
        if (this.opacity > 1) {
          return this.title_op = 'down';
        }
      } else if (this.title_op === 'down') {
        this.opacity -= (new Date()).getMilliseconds() / 25000;
        if (this.opacity < 0.1) {
          return this.title_op = 'up';
        }
      }
    };

    return TitleLabel;

  })(Label);

  MenuScene = (function(_super) {
    __extends(MenuScene, _super);

    function MenuScene() {
      MenuScene.__super__.constructor.call(this);
      this.bg = new Sprite(DISPLAY_WIDTH, DISPLAY_HEIGHT);
      this.bg.image = core.assets['./img/menu.png'];
      this.menuscenelabel = new MenuSceneLabel();
      this.menuscenekayo = new MenuSceneKayo();
      this.addChild(this.bg);
      this.addChild(this.menuscenelabel);
      this.addChild(this.menuscenekayo);
    }

    return MenuScene;

  })(Scene);

  MenuSceneLabel = (function(_super) {
    __extends(MenuSceneLabel, _super);

    function MenuSceneLabel() {
      MenuSceneLabel.__super__.constructor.call(this);
      this.text = '遊ぶゲームを選んでね！';
      this.width = core.width;
      this.font = '38px serif';
      this.y = 50;
      this.x = 390;
      this.color = 'rgb(251, 0, 126)';
    }

    return MenuSceneLabel;

  })(Label);

  MenuSceneKayo = (function(_super) {
    __extends(MenuSceneKayo, _super);

    function MenuSceneKayo() {
      MenuSceneKayo.__super__.constructor.call(this, 404, 178);
      this.image = core.assets['./img/kayo_menu2.png'];
      this.moveTo(395, 120);
    }

    MenuSceneKayo.prototype.ontouchend = function() {
      core.popScene();
      core.kayogamescene = new KayoGameScene();
      return core.replaceScene(core.kayogamescene);
    };

    return MenuSceneKayo;

  })(Sprite);

  KayoGameScene = (function(_super) {
    __extends(KayoGameScene, _super);

    function KayoGameScene() {
      KayoGameScene.__super__.constructor.call(this);
      this.bg = new Sprite(DISPLAY_WIDTH, DISPLAY_HEIGHT);
      this.bg.backgroundColor = 'wheat';
      this.bgaction = new KayoGameSceneBackAction();
      this.chara = new KayoGameSceneChara();
      this.staffs = [];
      this.staffCycle = 40;
      this.addChild(this.bg);
      this.addChild(this.bgaction);
      this.addChild(this.chara);
    }

    KayoGameScene.prototype.onenterframe = function() {
      var i, _results;
      if (core.frame % 50 === 0 && this.staffCycle > 10) {
        this.staffCycle -= 1;
      }
      if (core.frame % this.staffCycle === 0) {
        this.rin = new KayoGameSceneRin();
        this.addChild(this.rin);
        this.staffs.push(this.rin);
      }
      i = this.staffs.length;
      _results = [];
      while (i) {
        this.staff = this.staffs[--i];
        if (this.staff.intersect(this.chara)) {
          this.removeChild(this.staff);
          core.popScene();
          core.gameover = new KayoGameOverScene();
          _results.push(core.pushScene(core.gameover));
        } else if (this.staff.y > DISPLAY_HEIGHT) {
          _results.push(this.removeChild(this.staff));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return KayoGameScene;

  })(Scene);

  KayoGameSceneChara = (function(_super) {
    __extends(KayoGameSceneChara, _super);

    function KayoGameSceneChara() {
      KayoGameSceneChara.__super__.constructor.call(this, 73, 95);
      this.image = core.assets['./img/kayo_chara.png'];
      this.moveTo(DISPLAY_WIDTH / 2 - this.width / 2, DISPLAY_HEIGHT - this.height);
    }

    KayoGameSceneChara.prototype.onenterframe = function() {
      if (core.input.left) {
        this.scaleX = 1;
        if (this.x > 0) {
          this.x -= 12;
        }
      }
      if (core.input.right) {
        this.scaleX = -1;
        if (this.x < DISPLAY_WIDTH - this.width) {
          return this.x += 12;
        }
      }
    };

    return KayoGameSceneChara;

  })(Sprite);

  KayoGameSceneBackAction = (function(_super) {
    __extends(KayoGameSceneBackAction, _super);

    function KayoGameSceneBackAction() {
      KayoGameSceneBackAction.__super__.constructor.call(this, 205, 165);
      this.image = core.assets['./img/gohan_bg.png'];
      this.x = DISPLAY_WIDTH / 2 - this.width / 2;
      this.y = DISPLAY_HEIGHT / 2 - this.height / 2;
    }

    return KayoGameSceneBackAction;

  })(Sprite);

  KayoGameSceneRin = (function(_super) {
    __extends(KayoGameSceneRin, _super);

    function KayoGameSceneRin() {
      KayoGameSceneRin.__super__.constructor.call(this, 83, 144);
      this.image = core.assets['./img/kayo_rin.png'];
      this.x = Math.random() * (DISPLAY_WIDTH - this.width);
      this.y = -this.height;
    }

    KayoGameSceneRin.prototype.onenterframe = function() {
      return this.y += 10;
    };

    return KayoGameSceneRin;

  })(Sprite);

  KayoGameOverScene = (function(_super) {
    __extends(KayoGameOverScene, _super);

    function KayoGameOverScene() {
      KayoGameOverScene.__super__.constructor.call(this);
      this.bg = new Sprite(DISPLAY_WIDTH, DISPLAY_HEIGHT);
      this.bg.image = core.assets['./img/kayogameover.jpg'];
      this.addChild(this.bg);
    }

    KayoGameOverScene.prototype.ontouchend = function() {
      core.popScene();
      this.titleScene = new TitleScene();
      return core.pushScene(this.titleScene);
    };

    return KayoGameOverScene;

  })(Scene);

  window.onload = function() {
    var assets;
    core = new Core(DISPLAY_WIDTH, DISPLAY_HEIGHT);
    assets = [];
    assets.push('./img/title_name.png');
    assets.push('./img/title_back1.jpg');
    assets.push('./img/menu.png');
    assets.push('./img/kayo_menu2.png');
    assets.push('./img/bento1.jpg');
    assets.push('./img/kayo_chara.png');
    assets.push('./img/gohan_bg.png');
    assets.push('./img/kayo_rin.png');
    assets.push('./img/kayogameover.jpg');
    core.preload(assets);
    core.onload = function() {
      this.titleScene = new TitleScene();
      this.kayoGameScene = new KayoGameScene();
      return this.pushScene(this.titleScene);
    };
    return core.start();
  };

}).call(this);
