// Generated by CoffeeScript 1.7.1
(function() {
  var DISPLAY_HEIGHT, DISPLAY_WIDTH, Kasuri, KayoGameOverScene, KayoGameScene, KayoGameSceneBackAction, KayoGameSceneBomb, KayoGameSceneChara, KayoGameSceneRin, KayoGameSceneScore, KayoGameSceneTime, MenuScene, MenuSceneKayo, MenuSceneLabel, TitleLabel, TitleName, TitleScene, core,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  DISPLAY_WIDTH = 930;

  DISPLAY_HEIGHT = 620;

  enchant();

  core = {};

  TitleScene = (function(_super) {
    __extends(TitleScene, _super);

    function TitleScene() {
      TitleScene.__super__.constructor.call(this);
      this.bg = new Sprite(DISPLAY_WIDTH, DISPLAY_HEIGHT);
      this.bg.image = core.assets['./img/title_back1.jpg'];
      this.titlename = new TitleName();
      this.titlelabel = new TitleLabel();
      this.addChild(this.bg);
      this.addChild(this.titlename);
      this.addChild(this.titlelabel);
    }

    TitleScene.prototype.ontouchend = function() {
      core.menuScene = new MenuScene();
      return core.pushScene(core.menuScene);
    };

    return TitleScene;

  })(Scene);

  TitleName = (function(_super) {
    __extends(TitleName, _super);

    function TitleName() {
      TitleName.__super__.constructor.call(this, 657, 110);
      this.titleNameState = 'up';
      this.image = core.assets['./img/title_name.png'];
      this.x = 137;
      this.y = 255;
    }

    TitleName.prototype.onenterframe = function() {
      if (this.titleNameState === 'up') {
        this.y -= 1;
        if (this.y === 220) {
          return this.titleNameState = 'down';
        }
      } else if (this.titleNameState === 'down') {
        this.y += 1;
        if (this.y === 290) {
          return this.titleNameState = 'up';
        }
      }
    };

    return TitleName;

  })(Sprite);

  TitleLabel = (function(_super) {
    __extends(TitleLabel, _super);

    function TitleLabel() {
      TitleLabel.__super__.constructor.call(this);
      this.title_op = 'up';
      this.text = 'クリックしてスタート！';
      this.width = core.width;
      this.textAlign = 'center';
      this.font = '38px cursive';
      this.opacity = 0;
      this.y = 450;
      this.color = 'white';
    }

    TitleLabel.prototype.onenterframe = function() {
      if (this.title_op === 'up') {
        this.opacity += (new Date()).getMilliseconds() / 25000;
        if (this.opacity > 1) {
          return this.title_op = 'down';
        }
      } else if (this.title_op === 'down') {
        this.opacity -= (new Date()).getMilliseconds() / 25000;
        if (this.opacity < 0.1) {
          return this.title_op = 'up';
        }
      }
    };

    return TitleLabel;

  })(Label);

  MenuScene = (function(_super) {
    __extends(MenuScene, _super);

    function MenuScene() {
      MenuScene.__super__.constructor.call(this);
      this.bg = new Sprite(DISPLAY_WIDTH, DISPLAY_HEIGHT);
      this.bg.image = core.assets['./img/menu.png'];
      this.menuscenelabel = new MenuSceneLabel();
      this.menuscenekayo = new MenuSceneKayo();
      this.addChild(this.bg);
      this.addChild(this.menuscenelabel);
      this.addChild(this.menuscenekayo);
    }

    return MenuScene;

  })(Scene);

  MenuSceneLabel = (function(_super) {
    __extends(MenuSceneLabel, _super);

    function MenuSceneLabel() {
      MenuSceneLabel.__super__.constructor.call(this);
      this.text = '遊ぶゲームを選んでね！';
      this.width = core.width;
      this.font = '38px serif';
      this.y = 50;
      this.x = 390;
      this.color = 'rgb(251, 0, 126)';
    }

    return MenuSceneLabel;

  })(Label);

  MenuSceneKayo = (function(_super) {
    __extends(MenuSceneKayo, _super);

    function MenuSceneKayo() {
      MenuSceneKayo.__super__.constructor.call(this, 404, 178);
      this.image = core.assets['./img/kayo_menu2.png'];
      this.moveTo(395, 120);
    }

    MenuSceneKayo.prototype.ontouchend = function() {
      core.popScene();
      core.kayogamescene = new KayoGameScene();
      return core.replaceScene(core.kayogamescene);
    };

    return MenuSceneKayo;

  })(Sprite);

  KayoGameScene = (function(_super) {
    __extends(KayoGameScene, _super);

    function KayoGameScene() {
      core.keybind(16, "a");
      core.keybind(70, "b");
      core.keybind(32, "c");
      KayoGameScene.__super__.constructor.call(this);
      this.bg = new Sprite(DISPLAY_WIDTH, DISPLAY_HEIGHT);
      this.bg.backgroundColor = 'wheat';
      this.bgaction = new KayoGameSceneBackAction();
      this.chara = new KayoGameSceneChara();
      this.numberOfBomb = 3;
      this.bomblabel = new KayoGameSceneBomb(this.numberOfBomb);
      this.isOnceDoAmongPressKey = 0;
      this.staffs = [];
      this.kasuris = [];
      this.staffCycle = 40;
      this.pt = 0;
      this.gameTime = 0;
      this.time = new KayoGameSceneTime();
      this.scoreLabel = new KayoGameSceneScore(this.pt);
      this.addChild(this.bg);
      this.addChild(this.bomblabel);
      this.addChild(this.bgaction);
      this.addChild(this.time);
      this.addChild(this.scoreLabel);
      this.addChild(this.chara);
    }

    KayoGameScene.prototype.onenterframe = function() {
      var i, j, _results;
      this.gameTime += 1 / core.fps;
      if (core.frame % 20 === 0 && this.staffCycle > 10) {
        this.staffCycle -= 1;
      }
      if (core.frame % this.staffCycle === 0) {
        this.rin = new KayoGameSceneRin();
        this.addChild(this.rin);
        this.addChild(this.rin.kasuri);
        this.staffs.push(this.rin);
        this.kasuris.push(this.rin.kasuri);
      }
      i = this.staffs.length;
      j = this.kasuris.length;
      if (core.input.b && this.numberOfBomb > 0) {
        if (this.isOnceDoAmongPressKey === 0) {
          this.isOnceDoAmongPressKey = 1;
          while (i) {
            this.staffs.splice(i, 1);
            this.removeChild(this.staffs[--i]);
          }
          while (j) {
            this.kasuris.splice(j, 1);
            this.removeChild(this.kasuris[--j]);
          }
          this.removeChild(this.bomblabel);
          this.bomblabel = new KayoGameSceneBomb(--this.numberOfBomb);
          this.addChild(this.bomblabel);
        }
      } else {
        this.isOnceDoAmongPressKey = 0;
      }
      _results = [];
      while (i) {
        this.staff = this.staffs[--i];
        this.kasuri = this.kasuris[--j];
        if (this.kasuri.intersect(this.chara)) {
          this.removeChild(this.scoreLabel);
          this.scoreLabel = new KayoGameSceneScore(++this.pt);
          this.addChild(this.scoreLabel);
        } else if (this.kasuri.y > DISPLAY_HEIGHT) {
          this.removeChild(this.kasuri);
        }
        if (this.staff.intersect(this.chara)) {
          this.staffs.splice(i, 1);
          this.removeChild(this.staff);
          core.popScene();
          core.gameover = new KayoGameOverScene(this.gameTime.toFixed(2), this.pt);
          _results.push(core.pushScene(core.gameover));
        } else if (this.staff.y > DISPLAY_HEIGHT) {
          _results.push(this.removeChild(this.staff));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return KayoGameScene;

  })(Scene);

  KayoGameSceneChara = (function(_super) {
    __extends(KayoGameSceneChara, _super);

    function KayoGameSceneChara() {
      KayoGameSceneChara.__super__.constructor.call(this, 58, 95);
      this.image = core.assets['./img/kayo_chara.png'];
      this.moveTo(DISPLAY_WIDTH / 2 - this.width / 2, DISPLAY_HEIGHT - this.height * 1);
      this.scaleX = 1;
      this.scaleY = 1;
    }

    KayoGameSceneChara.prototype.onenterframe = function() {
      if (core.input.left) {
        this.scaleX = 1;
        if (core.input.a) {
          if (this.x > 0) {
            this.x -= 5;
          }
        } else {
          if (this.x > 0) {
            this.x -= 15;
          }
        }
      }
      if (core.input.right) {
        this.scaleX = -1;
        if (core.input.a) {
          if (this.x < DISPLAY_WIDTH - this.width) {
            return this.x += 5;
          }
        } else {
          if (this.x < DISPLAY_WIDTH - this.width) {
            return this.x += 15;
          }
        }
      }
    };

    return KayoGameSceneChara;

  })(Sprite);

  KayoGameSceneBomb = (function(_super) {
    __extends(KayoGameSceneBomb, _super);

    function KayoGameSceneBomb(num) {
      KayoGameSceneBomb.__super__.constructor.call(this);
      this.text = '残りボム数:' + num;
      this.color = 'darkred';
      this.moveTo(10, 10);
      this.font = '28px serif';
    }

    return KayoGameSceneBomb;

  })(Label);

  KayoGameSceneTime = (function(_super) {
    __extends(KayoGameSceneTime, _super);

    function KayoGameSceneTime() {
      KayoGameSceneTime.__super__.constructor.call(this);
      this.time = 0;
      this.text = this.time + ' 秒';
      this.x = DISPLAY_WIDTH - 200;
      this.y = 10;
      this.color = 'darkred';
      this.font = '28px italic';
    }

    KayoGameSceneTime.prototype.onenterframe = function() {
      this.time += 1 / core.fps;
      return this.text = this.time.toFixed(2).toString() + ' 秒';
    };

    return KayoGameSceneTime;

  })(Label);

  KayoGameSceneBackAction = (function(_super) {
    __extends(KayoGameSceneBackAction, _super);

    function KayoGameSceneBackAction() {
      KayoGameSceneBackAction.__super__.constructor.call(this, 205, 165);
      this.image = core.assets['./img/gohan_bg.png'];
      this.x = DISPLAY_WIDTH / 2 - this.width / 2;
      this.y = DISPLAY_HEIGHT / 2 - this.height / 2;
    }

    return KayoGameSceneBackAction;

  })(Sprite);

  KayoGameSceneRin = (function(_super) {
    __extends(KayoGameSceneRin, _super);

    function KayoGameSceneRin() {
      KayoGameSceneRin.__super__.constructor.call(this, 83, 144);
      this.kasuri = new Kasuri();
      this.image = core.assets['./img/kayo_rin.png'];
      this.x = Math.random() * (DISPLAY_WIDTH - this.width * 1.1);
      this.kasuri.x = this.x - 10;
      this.scaleX = 1.1;
      this.scaleY = 1.1;
      this.y = -this.height * 1.1;
      this.kasuri.scaleX = 1.1;
      this.kasuri.scaleY = 1.1;
      this.kasuri.y = -this.kasuri.height * 1.1;
    }

    KayoGameSceneRin.prototype.onenterframe = function() {
      this.y += 13;
      return this.kasuri.y += 13;
    };

    return KayoGameSceneRin;

  })(Sprite);

  Kasuri = (function(_super) {
    __extends(Kasuri, _super);

    function Kasuri() {
      Kasuri.__super__.constructor.call(this, 103, 144);
    }

    return Kasuri;

  })(Sprite);

  KayoGameSceneScore = (function(_super) {
    __extends(KayoGameSceneScore, _super);

    function KayoGameSceneScore(score) {
      KayoGameSceneScore.__super__.constructor.call(this);
      this.text = score + ' Pt';
      this.x = DISPLAY_WIDTH - 200;
      this.y = 50;
      this.color = 'darkred';
      this.font = '28px meiryo';
    }

    return KayoGameSceneScore;

  })(Label);

  KayoGameOverScene = (function(_super) {
    __extends(KayoGameOverScene, _super);

    function KayoGameOverScene(time, point) {
      KayoGameOverScene.__super__.constructor.call(this);
      this.bg = new Sprite(DISPLAY_WIDTH, DISPLAY_HEIGHT);
      this.bg.image = core.assets['./img/kayogameover.jpg'];
      this.datatime = new Label();
      this.datatime.backgroundColor = 'white';
      this.datatime.height = 50;
      this.datatime.textAlign = 'center';
      this.datatime.text = '時間：' + time;
      this.datatime.color = 'midnightblue';
      this.datatime.font = '48px serif';
      this.datatime.x = DISPLAY_WIDTH - 420;
      this.datatime.y = DISPLAY_HEIGHT - 200;
      this.datascore = new Label();
      this.datascore.backgroundColor = 'white';
      this.datascore.height = 50;
      this.datascore.textAlign = 'center';
      this.datascore.text = 'スコア：' + point;
      this.datascore.color = 'midnightblue';
      this.datascore.font = '48px serif';
      this.datascore.x = DISPLAY_WIDTH - 420;
      this.datascore.y = DISPLAY_HEIGHT - 100;
      this.addChild(this.bg);
      this.addChild(this.datatime);
      this.addChild(this.datascore);
    }

    KayoGameOverScene.prototype.ontouchend = function() {
      core.popScene();
      this.titleScene = new TitleScene();
      return core.pushScene(this.titleScene);
    };

    return KayoGameOverScene;

  })(Scene);

  window.onload = function() {
    var assets;
    core = new Core(DISPLAY_WIDTH, DISPLAY_HEIGHT);
    assets = [];
    assets.push('./img/title_name.png');
    assets.push('./img/title_back1.jpg');
    assets.push('./img/menu.png');
    assets.push('./img/kayo_menu2.png');
    assets.push('./img/bento1.jpg');
    assets.push('./img/kayo_chara.png');
    assets.push('./img/gohan_bg.png');
    assets.push('./img/kayo_rin.png');
    assets.push('./img/kayogameover.jpg');
    core.preload(assets);
    core.onload = function() {
      this.titleScene = new TitleScene();
      this.kayoGameScene = new KayoGameScene();
      return this.pushScene(this.titleScene);
    };
    return core.debug();
  };

}).call(this);
