// Generated by CoffeeScript 1.7.1
(function() {
  var DISPLAY_HEIGHT, DISPLAY_WIDTH, core;

  DISPLAY_WIDTH = 930;

  DISPLAY_HEIGHT = 620;

  enchant();

  core = {};

  window.onload = function() {
    var play_img;
    core = new Core(DISPLAY_WIDTH, DISPLAY_HEIGHT);
    play_img = [];
    play_img.push('');
    core.preload(gazou);
    core.onload = function() {};
    return core.start;
  };

}).call(this);
