// Generated by CoffeeScript 1.7.1
(function() {
  var DISPLAY_HEIGHT, DISPLAY_WIDTH, KayoGameScene, MenuScene, MenuSceneKayo, MenuSceneLabel, TitleLabel, TitleName, TitleScene, core,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  DISPLAY_WIDTH = 930;

  DISPLAY_HEIGHT = 620;

  enchant();

  core = {};

  TitleLabel = (function(_super) {
    __extends(TitleLabel, _super);

    function TitleLabel() {
      TitleLabel.__super__.constructor.call(this);
      this.title_op = 'up';
      this.text = 'クリックしてスタート！';
      this.width = core.width;
      this.textAlign = 'center';
      this.font = '38px cursive';
      this.opacity = 0;
      this.y = 450;
      this.color = 'white';
    }

    TitleLabel.prototype.onenterframe = function() {
      if (this.title_op === 'up') {
        this.opacity += (new Date()).getMilliseconds() / 25000;
        if (this.opacity > 1) {
          return this.title_op = 'down';
        }
      } else if (this.title_op === 'down') {
        this.opacity -= (new Date()).getMilliseconds() / 25000;
        if (this.opacity < 0.1) {
          return this.title_op = 'up';
        }
      }
    };

    return TitleLabel;

  })(Label);

  TitleName = (function(_super) {
    __extends(TitleName, _super);

    function TitleName() {
      TitleName.__super__.constructor.call(this, 657, 110);
      this.titleNameState = 'up';
      this.image = core.assets['./title_name.png'];
      this.x = 137;
      this.y = 255;
    }

    TitleName.prototype.onenterframe = function() {
      if (this.titleNameState === 'up') {
        this.y -= 1;
        if (this.y === 220) {
          return this.titleNameState = 'down';
        }
      } else if (this.titleNameState === 'down') {
        this.y += 1;
        if (this.y === 290) {
          return this.titleNameState = 'up';
        }
      }
    };

    return TitleName;

  })(Sprite);

  TitleScene = (function(_super) {
    __extends(TitleScene, _super);

    function TitleScene() {
      TitleScene.__super__.constructor.call(this);
      this.bg = new Sprite(DISPLAY_WIDTH, DISPLAY_HEIGHT);
      this.bg.image = core.assets['./title_back1.jpg'];
      this.titlename = new TitleName();
      this.titlelabel = new TitleLabel();
      this.addChild(this.bg);
      this.addChild(this.titlename);
      this.addChild(this.titlelabel);
    }

    TitleScene.prototype.ontouchstart = function() {
      core.menuScene = new MenuScene();
      return core.pushScene(core.menuScene);
    };

    return TitleScene;

  })(Scene);

  MenuSceneLabel = (function(_super) {
    __extends(MenuSceneLabel, _super);

    function MenuSceneLabel() {
      MenuSceneLabel.__super__.constructor.call(this);
      this.text = '遊ぶゲームを選んでね！';
      this.width = core.width;
      this.font = '38px serif';
      this.y = 50;
      this.x = 390;
      this.color = 'rgb(251, 0, 126)';
    }

    return MenuSceneLabel;

  })(Label);

  MenuScene = (function(_super) {
    __extends(MenuScene, _super);

    function MenuScene() {
      MenuScene.__super__.constructor.call(this);
      this.bg = new Sprite(DISPLAY_WIDTH, DISPLAY_HEIGHT);
      this.bg.image = core.assets['./menu.png'];
      this.menuscenelabel = new MenuSceneLabel();
      this.menuscenekayo = new MenuSceneKayo();
      this.addChild(this.bg);
      this.addChild(this.menuscenelabel);
      this.addChild(this.menuscenekayo);
    }

    return MenuScene;

  })(Scene);

  MenuSceneKayo = (function(_super) {
    __extends(MenuSceneKayo, _super);

    function MenuSceneKayo() {
      MenuSceneKayo.__super__.constructor.call(this, 404, 178);
      this.image = core.assets['./kayo_menu2.png'];
      this.moveTo(395, 120);
    }

    MenuSceneKayo.prototype.ontouchstart = function() {
      console.log('hoge');
      core.popScene();
      core.kayogamescene = new KayoGameScene();
      return core.replaceScene(core.kayogamescene);
    };

    return MenuSceneKayo;

  })(Sprite);

  KayoGameScene = (function(_super) {
    __extends(KayoGameScene, _super);

    function KayoGameScene() {
      KayoGameScene.__super__.constructor.call(this);
      this.bg = new Sprite(DISPLAY_WIDTH, DISPLAY_HEIGHT);
      this.bg.image = core.assets['./bento1.jpg'];
      this.addChild(this.bg);
    }

    return KayoGameScene;

  })(Scene);

  window.onload = function() {
    var assets;
    core = new Core(DISPLAY_WIDTH, DISPLAY_HEIGHT);
    assets = [];
    assets.push('./title_name.png');
    assets.push('./title_back1.jpg');
    assets.push('./menu.png');
    assets.push('./kayo_menu2.png');
    assets.push('./bento1.jpg');
    core.preload(assets);
    core.onload = function() {
      this.titleScene = new TitleScene();
      return this.pushScene(this.titleScene);
    };
    return core.start();
  };

}).call(this);
